bagcash_gerenciadorfinanceiro/GerenciadorFinanceiro/Models/Usuario.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GerenciadorFinanceiro.Models
{
    public class Usuario
    {
        public int UsuarioId { get; set; }

        public string Nome { get; set; }

        public string Email { get; set; }

        public IEnumerable<Transacao> Transacoes { get; set; }
    }
}

bagcash_gerenciadorfinanceiro/GerenciadorFinanceiro/Models/UsuarioViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace GerenciadorFinanceiro.Models
{
    public class UsuarioViewModel
    {
        [Required]
        public string Nome { get; set; }

        [Required, EmailAddress]
        [Display(Name = "E-mail")]
        public string Email { get; set; }

        [Required]
        public string Senha { get; set; }

        [Compare("Senha")]
        [Display(Name = "Confirme sua senha:")]
        public string ConfirmacaoSenha { get; set; }
    }
}

bagcash_gerenciadorfinanceiro/GerenciadorFinanceiro/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using GerenciadorFinanceiro.Models;
using GerenciadorFinanceiro.Services;
using WebMatrix.WebData;

namespace GerenciadorFinanceiro.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly UsuarioService usuarioService = new UsuarioService();
        // GET: Usuario
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Novo()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Adiciona(UsuarioViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    WebSecurity.CreateUserAndAccount(model.Email, model.Senha, new {Nome = model.Nome});
                    return RedirectToAction("Index", "Login");
                }
                catch (MembershipCreateUserException e)
                {
                    ModelState.AddModelError("usuario.Invalido", e.Message);
                    return View("Novo", model);
                }
            }
            else
            {
                return View("Novo", model);
            }
        }
    }
}

bagcash_gerenciadorfinanceiro/GerenciadorFinanceiro/Views/Usuario/Novo.cshtml
@model GerenciadorFinanceiro.Models.UsuarioViewModel

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")


@using (Html.BeginForm("Adiciona", "Usuario", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Novo Usuário</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmacaoSenha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmacaoSenha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmacaoSenha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}