bagcash_gerenciadorfinanceiro/GerenciadorFinanceiro/Controllers/CategoriaController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.Security;
using GerenciadorFinanceiro.Models;
using GerenciadorFinanceiro.Services;

namespace GerenciadorFinanceiro.Controllers
{
    public class CategoriaController : Controller
    {
        private readonly CategoriaService categoriaService = new CategoriaService();
        private readonly TransacaoService transacaoService = new TransacaoService();
        int userId = Convert.ToInt32(Membership.GetUser().ProviderUserKey);

        public ActionResult Index()
        {
            var categorias = categoriaService.GetAll();
            return View(categorias.ToList());
        }

        public ActionResult Create()
        {
            ViewBag.CategoriaId = new SelectList(categoriaService.GetAll(), "CategoriaId", "Descricao", new Categoria().CategoriaId);

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                categoria.UsuarioId = userId;
                categoriaService.Add(categoria);
                return RedirectToAction("Index");
            }
            return PartialView(categoria);
        }

        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Categoria categoria = categoriaService.GetById(id);
            if (categoria == null)
            {
                return HttpNotFound();
            }
            return View(categoria);
        }

        [HttpPost]
        public ActionResult Edit(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                categoriaService.Update(categoria);
                return RedirectToAction("Index");
            }
            return View(categoria);
        }

        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Categoria categoria = categoriaService.GetById(id);
            if (categoria == null)
            {
                return HttpNotFound();
            }
            return View(categoria);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Categoria categoria = categoriaService.GetById(id);
            categoriaService.Remove(categoria);
            return RedirectToAction("Index");
        }

        //public ActionResult CategoriasQuantificadas()
        //{
        //    var categoriasQuantificadas = new List<KeyValuePair<string, decimal>>();
        //    var categorias = db.Categorias;
        //    foreach (var item in categorias)
        //    {
        //        decimal valorTotalCategoria = db.Despesas.Where(x => x.CategoriaId == item.CategoriaId && x.DataVencimento.Month == DateTime.Now.Month).Sum(x => (decimal?)x.Valor) ?? 0;
        //        if (valorTotalCategoria > 0)
        //            categoriasQuantificadas.Add(new KeyValuePair<string, decimal>(item.Descricao, valorTotalCategoria));
        //    }
        //    return Json(categoriasQuantificadas, JsonRequestBehavior.AllowGet);
        //}

        public ActionResult PieChart()
        {
            var categorias = categoriaService.GetAll();

            var resultado = categorias.Select(x => new
            {
                label = x.Descricao,
                value =  transacaoService.GetAll().Where(y => y.CategoriaId == x.CategoriaId && y.DataTransacao.Month == DateTime.Now.Month).Sum(y => (decimal?)y.Valor) ?? 0
            }).ToList();

            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            categoriaService.Dispose();
        }
    }
}

bagcash_gerenciadorfinanceiro/GerenciadorFinanceiro/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GerenciadorFinanceiro.Models;
using WebMatrix.WebData;

namespace GerenciadorFinanceiro.Controllers
{
    
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Autentica(string email, string senha)
        {
            if (WebSecurity.Login(email, senha))
            {
                return RedirectToAction("Index", "Transacao");
            }
            else
            {
                ModelState.AddModelError("login.Invalido", "Login ou senha incorretos");
                return View("Index");
            }

            //Usuario usuario = usuarioService.GetUsuario(login, senha);
            //if (usuario != null)
            //{
            //    Session["usuarioLogado"] = usuario;
            //    return RedirectToAction("Index", "Transacao");
            //}
        }

        public ActionResult Logout()
        {
            WebSecurity.Logout();
            return RedirectToAction("Index");
        }

    }
}

bagcash_gerenciadorfinanceiro/GerenciadorFinanceiro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">


    <link href="~/css/style.css" rel="stylesheet">


    <title>@ViewBag.Title - BagCash</title>
    <script defer src="https://use.fontawesome.com/releases/v5.5.0/js/all.js" integrity="sha384-GqVMZRt5Gn7tB9D9q7ONtcp4gtHIUEW/yG7h98J7IpE3kpi+srfFyyB/04OV6pG0" crossorigin="anonymous"></script>
    <link href="~/fonts/fontawesome.min.css" rel="stylesheet" />
    <link href="~/Content/JSFiddle.css" rel="stylesheet" />
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar " style="background-color: #00BFFF;">
        <div class="container-fluid">
            <ul class="nav nav-tabs">
                <li>
                    <a href="@Url.Action("Index", "Transacao")" class="navbar-dark">
                        <img src="~/Image/profit (1).png" />
                        BagCash
                    </a>
                </li>

                <li><a href="@Url.Action("Index", "Transacao")" class="navbar-brand">Transações</a></li>
                <li><a href="@Url.Action("Index", "Categoria")" class="navbar-dark">Categorias</a></li>

                @if (User.Identity.IsAuthenticated)
                {
                    <li>@Html.ActionLink("Logout", "Index", "Login")</li>
                }
                else
                {
                    <li>@Html.ActionLink("Login", "Logout", "Login")</li>
                }
            </ul>
        </div>
    </nav>
    <div class="container body-content">

        @RenderBody()
        <hr />
        <footer>
            <div class="text-center">
                <br />
                <br />
                <p>Bag Cash Corporation</p>
                <p>Desenvolvido por</p>
                <p>João Vitor & Paulo Ferreira</p>
                <p>&copy; @DateTime.Now.Year</p>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)



</body>
</html>